import "@/styles/globals.css";
import "@/styles/satoshi.css";
import Image from "next/image";
import Link from "next/link";
import { Suspense } from 'react';
import { Toaster } from 'react-hot-toast';


 export const metadata = {
  title: 'El Bigodon',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="pt_BR">
      <body suppressHydrationWarning={true}>
        <Toaster position="top-right" reverseOrder={false}/>
        <Suspense>
        <div className="rounded-sm border border-stroke bg-black shadow-default dark:border-strokedark dark:bg-boxdark">
        <div className="flex flex-wrap items-center">
          <div className="hidden w-full xl:block xl:w-1/2">
            <div className="py-17.5 px-26 text-center">
              <Link className="mb-5.5 inline-block" href="/">
                <Image
                  className="hidden dark:block"
                  src={"/images/logo/logo-inline.png"}
                  alt="Logo"
                  width={176}
                  height={32}
                />
                <Image
                  className="dark:hidden"
                  src={"/images/logo/logo-inline.png"}
                  alt="Logo"
                  width={176}
                  height={32}
                />
              </Link>

              <p className="2xl:px-20"></p>

              <span className="mt-15 inline-block">
                <Image
                  className="hidden dark:block"
                  src={"/images/elbigodon/El_Bigodon_logo.png"}
                  alt="Logo"
                  width={238}
                  height={64}
                />
                <Image
                  className="dark:hidden"
                  src={"/images/elbigodon/El_Bigodon_logo.png"}
                  alt="Logo"
                  width={238}
                  height={64}
                />
              </span>
            </div>
          </div>

          <div className="w-full border-stroke dark:border-strokedark xl:w-1/2 xl:border-l-2">
            <div className="w-full p-4 sm:p-12.5 xl:p-17.5">
                {children}
              </div>
            </div>
          </div>
        </div>
        </Suspense>
      </body>
    </html>
  )
}
